# Generated by Django 2.0.9 on 2018-10-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('state', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('img_path', models.FilePathField(path='/static/img/', recursive=True)),
            ],
        ),
    ]
