# Generated by Django 2.0.9 on 2018-10-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_path',
            field=models.CharField(max_length=300),
        ),
    ]
