# Generated by Django 2.0.9 on 2018-10-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181009_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumb_path',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
